version: '3.8'

services:
  backend:
    container_name: mates-backend
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    networks:
      - mates-network

  postgres:
    image: postgres:15
    container_name: mates-postgres
    restart: always
    environment:
      POSTGRES_USER: anuragshrestha
      POSTGRES_PASSWORD: Hello@123
      POSTGRES_DB: mates_app
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mates-network

  redis:
    image: redis:latest
    container_name: mates-redis
    ports:
      - "6379:6379"
    networks:
      - mates-network

volumes:
  pg_data:

networks:
  mates-network: